apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpi-cluster
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # Nunca deixe mais de 1 pod fora do ar
      maxSurge: 1 
  selector:
    matchLabels:
      app: mpi-container
  template:
    metadata:
      labels:
        app: mpi-container
    spec:
      containers:
      - name: mpi-container
        image: docker.io/library/pspd:latest
        imagePullPolicy: Never  # Evita que o Kubernetes tente baixar a imagem
        ports:
        - containerPort: 22  # Porta SSH
        command: ["/bin/bash", "-c", "/setup.sh" ]
        securityContext:
          privileged: true
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: mpi-service
spec:
  selector:
    app: mpi-container
  ports:
  - name: ssh
    protocol: TCP
    port: 22  # Porta do serviço Kubernetes
    targetPort: 22  # Porta dentro dos pods
  type: ClusterIP  # Mantém a comunicação interna

